### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Aesop112** [Hotrian/OpenVRDesktopDisplayPortal#19]
1. Keyboard hotkeys for each slider and +/-.
2. I don't know what alpha means but I'm guessing it's transparency? Better label?
3. The slider values are really extreme and your Vr pip (picture in picture) fly off into somewhere, very far.
4. \+ and - on each side of sliders for finer control
5. An option to have a bold outline and maybe a color of outline around pip may be nice for some environments. 
6. This app is not listed yet in r vives "applications" list (at the bottom). Only your twitch chat viewer. https://www.reddit.com/r/Vive/wiki/index#wiki_applications.3A

Keep up with the updates my friends and let r vive know, hopefully get some more donations! 
Thanks!

**Comment by Hotrian** [comment]
1. I'll see what I can do, but I suspect these will be useless when #18 is finished. These probably would only work when the application has focus, because I don't know if Unity can detect input from the background (Could be used for Keylogging, which is why I believe this is unsupported, but I'll find out), making it even a bit less useful.
2. [Alpha](https://en.wikipedia.org/wiki/Alpha_compositing) is an extremely common term used in computer graphics. I suppose I could rename it but then it would technically be incorrect. When the value is 1 Transparency that would imply full transparency. 0 Transparency would imply it was fully visible. 1 Alpha implies it is opaque. 0 Alpha implies it is fully transparent.
3. This is correct. I'll see what I can do.
4. These would be nice, but you can use the input fields for finer control for now.
5. Not sure I can do this because I'm just using SteamVR Overlays. I cannot draw typical geometry, just overlays, so I would have to draw another overlay just slightly behind, and just slightly larger, which probably wouldn't look good in all cases.
6. I didn't even add my OpenVR Twitch Chat there! Someone else must have :). Good to know people are looking out :).

Thanks for the suggestions! I'll see what I can do :).

**Comment by Hotrian** [comment]
For some reason I set the limits on the XYZ sliders to -10/+10. Not sure why I thought they should be so high (since this should equate to 10 meters), as it becomes a little useless when overlays always draw on top, and you can enter any number into the input fields (I tested up to 200, but who needs an overlay 200 meters from them :P). I guess before I had tooltips going (since thay are not a built in Unity behaviour) I was concerned people would think the slider showed the only valid values, and someone would complain it was too close, since depth still applies to the overlay, even if it always draws on top. 

Perhaps I could change the behaviour so when you enter a value into the input field, it becomes the new base value for the slider, and the slider allows adjustments -1/+1 or something more useful and controllable.

**Comment by Hotrian** [comment]
I've fixed all of these except number 5 as of the latest release (coming in an hour or so; after I do some more in depth testing to ensure I didn't introduce any bugs). I'll be closing this issue and opening a separate one for number 5 with my next commit.
