### ISSUE TITLE
 requests and such

### ISSUE THREAD

**Issue by Aesop112** [Hotrian/OpenVRDesktopDisplayPortal#21]
This one your not going to like. Have you used big screen betavr? Basically you hold a grip button on your screen and you can move it, or hold it and click up or down on track pad for distance or left or right for curvature. It might be primetime ready if this were configurable IN Vr with your controllers. Totally unstandable if not ^_^

Another would be- you know how you can set it to look at it and it will scale and alpha? Could you make it so the screen would dodge your direct vision? As in get out of the way so I can see over there lol. I suppose you could set the alpha 1 to 0. Idk, what do you think?

The last one is the scale and alpha need +- buttons.

Any way to set the app to launch with specific games and connect a profile to load with certain games?

**Comment by Hotrian** [comment]
1. Controller integration is in the works #18 
2. Moving it to dodge your gaze might be kind of tricky. It would actually require two overlays, one to house your content, and the second would be an invisible overlay that only detected gaze. Might be pretty tricky but I'll look into it.
3. I'm concerned that adding 12 extra buttons down there might make that panel a bit crowded, but I'll try it out and see how it goes.
4. As far as I know SteamVR doesn't pass information out regarding which application is drawing. I could make it auto load profiles when certain exes are detected, but it would be unreliable because you can launch multiple games at once (I once forgot I minimized Project Cars, and started up a different game and was playing for half an hour before I realized Project Cars was minimized in the background and had paused it's rendering..). Right now it auto-loads the last loaded profile when it starts, but there is no other auto-load feature currently.

**Comment by Hotrian** [comment]
1. With release v1.0.5 Controllers have been integrated! It is now possible to move/rotate the overlays by touching them with a controller and holding the trigger down. You can scale the overlays by grabbing one to move/rotate it, then hold down the second controller's trigger and bring the controllers closer together or further apart, then release the second trigger. Wash, Rinse, Repeat, until you have the Overlay at the scale you want. Watch out for #28 though ;]. v1.0.5 also adds Mouse Simulation support so you can send clicks to the target application by aiming at the overlay and pulling the trigger (left click) or clicking the Touchpad (right click). Also see #27. See [the v1.0.5 release page](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/releases/tag/v1.0.5-alpha) for a lot more info.
2. I'm still considering adding this, but the last time I checked the SteamVR API, it isn't possible to create a _completely_ clear Overlay (the closest I can get is a very light, almost fully transparent, overlay). I think this might be because the C# side of things seems to be missing a few signatures for the C++ calls, but I can't really tell right now. I have a few tricks up my sleeve, but nothing would work as cleanly as a second invisible Overlay that actually responds to your gaze but manipulates the main Overlay. I still think it would be very nice though so I'm still thinking about implementing this. It might be acceptable even if the second overlay isn't fully transparent, since it would be a bit of a "ghost" Overlay that essentially tells you where the overlay is 'really' anchored. I'll try it out and see what I think.
3. Also still considering this, but I'm not certain it's necessary as I'm moving away from the Desktop UI and moving things into VR for VR controls and potentially a VR UI that can be toggled on and off from VR for the Overlay. Still, it could be handy in several situations, and doesn't really negatively affect anything, so I'll see about adding these for the next release.
4. It's also still not out of the question to auto-load a given profile when a given application has been detected. Again, I don't believe the SteamVR API makes the identity of the current rendering application available anywhere, but it _is_ totally possible to detect when an application opens, so I could potentially add this, and I think it would be nice, but it would be somewhat finicky as it would only kick in when an application _first_ loaded. I think it might work out fine, but I won't know until I attempt implementation.

Just keeping you updated on my current thoughts and letting you know I didn't just forget about your requests :). I seriously value the input, as probably half of the features in OVRDDP are due to requests. I think I will implement all of these requests, but I might decide later that I don't like the implementation or the aesthetic, and they might not make the cut or might be delayed for another time when they can be properly implemented.

I'll continue to keep this issue updated, but I plan to either implement or deny these requests by the next release, so I'm marking this issue for the next release.

**Comment by Hotrian** [comment]
Okay! So I'm ready to close this one pretty soon:
1. Controllers have been integrated. Support can be improved but you can currently grab a 'World' Overlay using the controllers, and with that you can move/rotate it or by using both controllers you can scale it. There is also support for mouse simulation. v1.0.6 will have much better options for controlling these.
2. I decided to add this! Using #30 I was able to implement a new animation type that dodges your gaze. This works for Controller, World, and Screen Overlays though it seems kind of pointless for Screen Overlays since the gaze detection is always either hitting or missing the Overlay depending on it's location, so this animation basically does nothing :P Still debugging but this will make v1.0.6
3. I've decided not to implement these extra buttons because they will crowd the interface; Instead, #31 adds support for the ScrollWheel on all of the Input Fields and Sliders. This isn't quite the same and there isn't an easy hotkey to edit these, but I'm concerned about adding another 12 hotkeys anyway. If you really need buttons/hotkeys for these let me know though and I'll reconsider it.
4. I've decided not to implement this because it would require making a rather large database of all of the OpenVR titles available so I can detect which one is currently being used. Since I don't want to dedicate that much time into logging all of the VR titles I won't be implementing this one for now. If [the OpenVR API](https://github.com/ValveSoftware/openvr/wiki/API-Documentation) ever implements a method for getting the currently drawing process or someone releases an easy to parse, complete list of OpenVR titles, however, I will reconsider this as well.

I'm still doing some work on 1 and 2, but I will be closing this soon in preparation for v1.0.6.
