### ISSUE TITLE
I can't resize Youtube fullscreen video after locking aspect ratio.

### ISSUE THREAD

**Issue by Viperlotus** [Hotrian/OpenVRDesktopDisplayPortal#50]
Hello.  I'm using version 1.0.6 of this program, and I seem to be having an issue.  When I put a Youtube video in fullscreen, then target it and lock the aspect ratio, the window does not change size in VR after resizing it in the program.  According to the instructions for this program, I should be able to do that, unless I misunderstood them.

**Comment by Hotrian** [comment]
Hmm. It sounds like you are doing it correctly. I just tested this myself and it seems to work fine. Are you pressing the Enter key after typing in a new height? What browser are you using?

**Comment by Hotrian** [comment]
Can you also try running OVRDDP as an Admin, in case this is a permissions issue?

(I would have edited my last comment but I'm mobile now and apparently my GitHub app doesn't support that..)

**Comment by Viperlotus** [comment]
Thank you for replying.  I tried running every piece involved (Firefox browser, Steam, SteamVR, OVRDDP and Elite: Dangerous) as admin all at once and hitting enter after typing in the new height, but it doesn't seem to make a difference.  What browser do you use?

**Comment by Hotrian** [comment]
I'm using Firefox 49.0.2.

> the window does not change size in VR after resizing it 

To be clear though, this shouldn't change the size of the window in VR; it changes the size of the window on your desktop so that it can be captured at a higher FPS. You can change the size of the window in VR using the gestures (if it's a World overlay) or using the input boxes in the bottom right of the main window.

[Here is an example](http://i.imgur.com/SEFX1BN.png) of a "fullscreen" Youtube video that has been resized to 360p.

**Comment by Viperlotus** [comment]
> You can change the size of the window in VR using the input boxes in the bottom right of the main 
>  window.

Oh.  Well, that's what I was misunderstanding before, then.  I tried adjusting those boxes and I got the window exactly how I wanted it to be.  Thank you very much, sorry about the confusion.

**Comment by Hotrian** [comment]
No problem, it was my misunderstanding as well :). The UI is in need of some serious refinement, but at least for now everything seems to be working as it should, and once you understand what everything does it all works pretty well :). There are definitely some improvements to be made, but for an "alpha" I would say everything is going along pretty great so far.

I'm closing this issue since it sounds like I solved your problem. Feel free to reopen or open another as needed though.
