### ISSUE TITLE
Background Hotkey Input and Configurable Hotkeys

### ISSUE THREAD

**Issue by ArmEagle** [Hotrian/OpenVRDesktopDisplayPortal#54]
It's great that I can toggle the overlay on and off with spacebar. But it would make things a lot easier if the program could use a (preferably configurable) hotkey that would work without it having focus.

**Comment by Hotrian** [comment]
**Edit: See down below for a proper solution.**

~~I could make the hotkey configurable, but unfortunately Unity can only capture input while the application has focus to prevent keyloggers, etc. It's probably possible to grab the keyboard input directly but I'm not certain this is possible with Unity.~~

~~**Edit: See below for a version with Background Input.**~~

**Comment by Hotrian** [comment]
**Edit: See down below for a proper solution.**

~~Okay, I made a custom version for now until these options are pushed into the repo.~~

~~[OpenVRDesktopDisplayPortal-v1.0.6.2.zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/files/573219/OpenVRDesktopDisplayPortal-v1.0.6.2.zip)~~

~~This version now uses custom Inputs, but there's a trick to accessing the Input options.~~

~~\- Unzip the file somewhere,~~
~~\- Create a shortcut to the exe,~~
~~\- Right click the shortcut and go to Properties,~~
~~\- In the target box, add a space followed by `-show-screen-selector`. [Example](http://image.prntscr.com/image/997f03839e864281b622a6975ffa33a2.png)~~
~~\- Now, when you launch the shortcut, you will get [this dialog](http://image.prntscr.com/image/591edb25cefe4921a49fb71e917f3a45.png).~~
~~\- [Scroll down to "Toggle Overlay"](http://image.prntscr.com/image/c32123e031b84d31a8e3cbf224d8fb45.png), and double click it the old hotkey to replace it.~~
~~\- I also added the Overlay shift hotkeys to the Input Manager as configurable hotkeys.~~

~~I also made a different version that always shows the screen selector:
[OpenVRDesktopDisplayPortal-v1.0.6.2.1.zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/files/573228/OpenVRDesktopDisplayPortal-v1.0.6.2.1.zip)~~

~~This one doesn't require the shortkey trick, but will always show the screen selector when you launch it, which is an added step I prefer to avoid :P.~~

~~I'll probably skip the Input Manger and add a system for customizing the Hotkeys directly from within the app in the future, but for now either one of these will allow you to customize the Hotkeys.~~

~~**(Edit: It seems launching the exe directly in 1.0.6.2 does not keep the Input changes like I thought it did :( In that case I recommend the second link, 10.6.2.1; Like I say down below, I'll make a custom input manager for configurable hotkeys in the future so you can skip the screen selector step)**~~

**Comment by Hotrian** [comment]
Turns out I can hook the keyboard input from the background on Windows (which is the only place OVRDDP will run right now anyways). Adding configurable keys will take a while, but for right now I can make a custom version for you that accepts background input on certain keys. 

Which Hotkeys would you like to run from the background, and which keys would you like them mapped to?

Right now I have A-Z, F1-F12, and Control, Shift, Spacebar, Backspace, Tilde/Grave, and Enter mapped out. I could probably map any other key very easily, though right now it doesn't support combo keys (like Shift+A vs just A). 

I'm expecting a list like:
- Toggle Overlay = F6
- Yaw - = F8
- Yaw + = F9

But it's fine in any other format. 

It will still be a bit before I have my new Hotkey Manager up and running, but shouldn't be too long now.

**Comment by Hotrian** [comment]
**Edit: See down below for a proper solution.**

~~I have two more demo versions for you!~~
- ~~[OpenVRDesktopDisplayPortal-v1.0.6.2.2.zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/files/573352/OpenVRDesktopDisplayPortal-v1.0.6.2.2.zip) has all the keys working from the background! Check the [Hotkeys part of the Instructions](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/wiki/Instructions#hotkeys) for a reminder on all the hotkeys. **Do note `S` is the Screenshot key on SteamVR, so if the Display Mirror has focus and you press `S`, SteamVR will appear to freeze for a bit!** If you need/want the Display Mirror to be full screen, just full screen it, then select the SteamVR Status Window and drag it into the corner. With the SteamVR Status Window in focus, you shouldn't have any issues, since none of the hotkeys seem to conflict with it except `Spacebar` which opens the context menu thingy, but none of the hotkeys seem to interact with it otherwise. Another option is to open Notepad and type into that instead.~~
- ~~[OpenVRDesktopDisplayPortal-v1.0.6.2.3.zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/files/573353/OpenVRDesktopDisplayPortal-v1.0.6.2.3.zip) only has the `Spacebar` key, which Toggles the Overlay, using the new Background Input system. The other Hotkeys will continue to function as before, and only work if OVRDDP has focus.~~

~~If you need any of the keys mapped to something else, just let me know and I'll throw up a custom version with special hotkeys for now. I'll probably derp up a Hotkey Customization panel in a little bit, but no promises on ETA.~~

~~**Edit:**~~

~~I forgot in these versions I accidentally renamed the save folder, just copy your folder at
`C:\Users\<USERNAME>\AppData\LocalLow\HeadlessOverlayToolkit\OpenVRDesktopDisplayPortal`
and rename it to
`OpenVRDesktopDisplayPortal v1_0_6_2`
and you're good to go :o.~~

**Comment by Hotrian** [comment]
Okay, I have another experimental version for you! Sorry for spamming your inbox :).

This one has a new Hotkey Configuration panel that lets you change the hotkeys from within the application. It also has the ability to turn Background Input on/off for any of the hotkeys. Currently it does not save any Hotkey settings, so you'll have to reconfigure them each time you start OVRDDP (sorry for that, but it would take quite a bit of work and I wanted to get this out ASAP). This version also fixes the save bug mentioned in my last comment.

To change a Hotkey:
- Open the Hotkey Settings panel with the button on the top left
- Click the button next to the action you want to change (the button is labelled with the current Hotkey)
- Press the key you want mapped
- To cancel, press Escape instead
- To disable that action, press Backspace instead

You can close the Hotkey Panel again by clicking the Hotkey Settings button again.

The toggle on the right of each hotkey controls whether or not that hotkeys works in the background. When checked on, that hotkey works in the background. When checked off, it only works while OVRDDP has focus.

There are still some things to work out, but right now it seems fully functional. I noticed if OVRDDP is getting a bad capture rate, and you hold the key down, it can sometimes keep pressing the key for a second or two. If OVRDDP is getting a good capture rate, this doesn't seem to be an issue, so this issue will go away once I implement a better capture method.

[OpenVRDesktopDisplayPortal-v1.0.6.2.4.zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/files/573490/OpenVRDesktopDisplayPortal-v1.0.6.2.4.zip)

Edit: Sorry for the funny version numbering also :). The `.2` is because this is the second experimental build off the `1.0.6` main version. The `.4` is because it is the fourth iteration of the second experimental build. It does not have the code changes from `v1.0.6.1`, which [can be found here](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/issues/51#issuecomment-256236950), so `.2` is more like a sister branch off the main repo and not a direct upgrade from `.1`.

I have a few different pots in the fire right now ;]

**Comment by ArmEagle** [comment]
Wow! Such quick response! I tried out the .2.3 version for a bit.

I'm using OVRDDP to show a window inside Elite Dangerous. Setting it up to a position to my liking took some fiddling. But I don't think I'd go through the trouble of wanting dedicated background hotkeys for that. Though clumsy I could manage with quick moving the HMD up to my forehead and back and positioning my mouse cursor (couldn't get the grab&drag with controller to work then).

Any hotkey for the toggle could clash with something for whatever game. But in Elite I could free up the spacebar. So that simple version was just fine for my use case!

I should really look into getting the required tools running so I can play around with this code and compile it myself. But thank you so far!

... And just moments before I was ready to post you have a new version. I'll give that a run too. I'll probably stick with the default hotkeys as otherwise I'd have to set it up every time I start it as you mention.

Awesome work!

**Comment by Hotrian** [comment]
This is now in OVRdrop, which is the closed source Steam Release of OVRDDP. Since I will continue to incorporate feature requests from OVRDDP into OVRdrop, I am closing this issue now.

If you are interested, you can find OVRdrop on Steam [here](http://store.steampowered.com/app/586210).
