### ISSUE TITLE
Side by side content?

### ISSUE THREAD

**Issue by duig0** [Hotrian/OpenVRDesktopDisplayPortal#56]
Would it be possible to display side by side content full screen with each image displayed correctly in side by side?

Thanks in advance

**Comment by Hotrian** [comment]
~~Not that I know of. The OpenVR API does not allow you to control the display to eye in this way. You feed a single texture in, and the Compositor handles turning them into Overlays and displaying them.~~

~~Edit: You can display multiple Overlays, but you can't display a single overlay to a given eye or set a texture that can display one side per eye. OpenVR does not currently have an API for these last I checked.~~

Edit2: Looks like this was wrong, see [my comment here](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/issues/56#issuecomment-274273024).

**Comment by duig0** [comment]
Many thanks for your reply.

**Comment by Aesop112** [comment]
What an awesome idea

**Comment by Hotrian** [comment]
~~Too bad it is not currently possible using the Overlay system :P~~

**Comment by Aesop112** [comment]
It is, maybe someday

**Comment by Hotrian** [comment]
Holy shit, they ****ing added this in the latest SteamVR API :o!

Will see about implementing it for future releases, though I'm not sure exactly what has changed in the SteamVR API and if updating to the latest will screw up OVRDDP or not - it might be super simple to implement, or it might be very difficult.

**Comment by Hotrian** [comment]
Wow was I wrong about this. It wasn't available in the SteamVR Unity Plugin, but it actually was available in the SteamVR API. Looks like it was added to the SteamVR API back in May 2016, but I had no idea it was available in the C code because it wasn't added to the C# code yet. The C# code is quite outdated, unfortunately. I possibly could have added support for it to the C# side, but I hadn't gone digging through the C code enough to know it existed.

Will look into adding Side By Side support in the future, though I don't know if it will break anything or if it will work properly.

Edit: Totally works. Will be adding SBS support in the future. SteamVR does seem to have support for flipping the left and right eyes too (incase your source file is inverted) but this doesn't seem to do anything. With the next release of OVRDDP you'll also be able to watch Full HD content (Windows 8+ only), so this will be pretty great :D

Edit: Figured out how to fix inverted mode (where the left half is shown to the right eye, and vice versa). Looks like they screwed up in the API and used the wrong flag somewhere, and I just happened to find the correct flag :o.

**Comment by Hotrian** [comment]
This is now in OVRdrop, which is the closed source Steam Release of OVRDDP. Since I will continue to incorporate feature requests from OVRDDP into OVRdrop, I am closing this issue now.

If you are interested, you can find OVRdrop on Steam [here](http://store.steampowered.com/app/586210).
