### ISSUE TITLE
Accidentally saved over default profiles

### ISSUE THREAD

**Issue by CoreyJ87** [Hotrian/OpenVRDesktopDisplayPortal#58]
Where is this data stored? I tried deleting the OVRDDP folder and unzipping it fresh. It still has the old saved profiles.

**Comment by Hotrian** [comment]
You can recover the default profiles by deleting all of your existing profiles - that should regenerate the defaults.

Otherwise, the save files are located at `C:\Users\<USERNAME>\AppData\LocalLow\HeadlessOverlayToolkit\OpenVRDesktopDisplayPortal` for now. The profiles should be saved in the `savedProfiles.gd` file. I'll be switching to another format in the future, probably XML, but for now I think it is fine.

**Comment by CoreyJ87** [comment]
Awesome. Thanks for the quick reply. BTW awesome work here. I love it so far(besides me being dumb). This is gonna be sooooo useful
