### ISSUE TITLE
Low FPS When Playing Videos

### ISSUE THREAD

**Issue by nemesisupreme** [Hotrian/OpenVRDesktopDisplayPortal#61]
Hi,

To give context. I'm interested in playing elite dangerous via Steam VR while playing a youtube video in a small window.

Maybe I'm just selecting the wrong settings but whenever I do this, the fps I get from the youtube window is like 10fps. This is usually unheard of for me to have low fps like this. Anything I can adjust in the settings to alleviate this?

**Comment by Hotrian** [comment]
The public version of OVRDDP can only capture about a 360p window at 24FPS+, depending on hardware. The public version is not GPU accelerated so is limited by your CPU. You can full screen Youtube and then target it, lock the aspect, and resize the window using the resolution controls. This is done using numbers 14 and 16 on [the Desktop Controls Key](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/wiki/Instructions#desktop-control-key).

I took the source closed source and explained my reasoning [here on Reddit](https://www.reddit.com/r/Vive/comments/5d4576/so_i_rigged_up_a_solution_for_keeping_an_eye_on/da2au3v/?context=10000). I'm currently in talks with Valve to get this on Steam, and that version will be able to capture your full desktop at 150+FPS. It can capture my 1440p monitor at about 500FPS, using an R7 265 which is way below spec for VR.

If for some reason my application can not be posted on Steam, I will release the faster version here on GitHub in a few months.

**Comment by Hotrian** [comment]
Just an update regarding the Steam version:

I'm still waiting on the Steam onboarding process. They keep telling me I will be on Steam and then don't actually add me to the Steamworks section. You can sign up to the Steamworks site, but there's no magic button - you have to wait for Valve to add your app to Steamworks before you can do anything.

As soon as Valve actually adds me on Steam OVRDDP should be available shortly - though I'm planning to change the name before a Steam launch.

**Comment by Hotrian** [comment]
Just another update - I've now officially been onboarded and this _will_ be on Steam. Release date still to be determined; still working out all the kinks and getting everything the way I want it before release. Stay tuned!

**Comment by nemesisupreme** [comment]
Hey, just wanted to check in. How's it going with the steam integration?

**Comment by Hotrian** [comment]
Everything is going good so far! I just need a few more things to be completed and it should be ready for launch :).

**Comment by Hotrian** [comment]
I am closing this issue now because OVRdrop is due for release tomorrow! OVRdrop can clone my entire monitor (2560x1440) at 500+ FPS, though it will typically cap out at 200~ FPS because the new API will only capture a screenshot of your monitor when something changes, and it's quite hard to update your screen faster than 200 FPS :).

Support for full desktop capture will be coming in a future release, but right now I'm preparing to fix any bugs that are found after release :).

Either way, you should definitely be able to capture a video now - full screen or not :).

If you are interested, you can find OVRdrop on Steam [here](http://store.steampowered.com/app/586210).
