### ISSUE TITLE
ERROR OCCURRING WHEN RUNNING .EXE FILE AFTER DOWNLOAD

### ISSUE THREAD

**Issue by mwal0120** [Hotrian/OpenVRDesktopDisplayPortal#62]
Hi,
I have just downloaded the OpenVRDesktopDisplayPortal-v1.0.6.zip and ran it and I'm getting the following error:-
DATA FOLDER NOT FOUND - There should be 'OpenVRDesktopDisplayPortal-v1.0.6_Data'
folder next to the executable.

There is a folder there called that though.
I have tried downloading the other 2 files, Source code (zip) and Source code (tar.gz) but still get the same result.
I am running Windows 8 but do not use Steam.
Any ideas?
Mick

**Comment by Hotrian** [comment]
Not sure about the Data folder issue, but this is made for SteamVR/OpenVR so you definitely need to use SteamVR to run this. Can you use SteamVR without having Steam installed?

Will check the Data folder issue right now.

**Comment by Hotrian** [comment]
Just tested and am not having issues running the latest public release. You used [OpenVRDesktopDisplayPortal-v1.0.6.zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/releases/download/v1.0.6-alpha/OpenVRDesktopDisplayPortal-v1.0.6.zip) from [this page](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/releases/tag/v1.0.6-alpha)? Did you extract the archive? I don't think it will work properly unless you extract the files first.

Edit: I just tried running the exe from inside the zip without extracting it and got the error you posted about. If you didn't already, can you try extracting the exe and the Data folder somewhere like your Desktop before running the exe?

**Comment by mwal0120** [comment]
Hi,

Thanks for coming back so quickly.

I don't use Steam VR at all. However, this issue is happening even before I can try the program. As I download the file from the web page my operating system gives me the option to "open when downloaded", I click this and after a few seconds I'm presented with the .exe file and a folder (unzipped) in an open window. I double click the .exe file and within a second I see the program try to open (faint flash of a green progress bar) and then that error message appears, both .exe and the unzipped folder are in the same master folder.

I am downloading the file from a link posted by BUMBLE, I notice your link has ONLY 1.0.6 Alpha listed where as Bumble's link has all the previous releases on.

Many thanks,

Mick and Jackie Walpole
Bwthyn Bach, Bala
07721 022565
info@PrivateCottageInWales.com
www.PrivateCottageInWales.com

**Comment by mwal0120** [comment]
Hi,
Just tried from clicking your links and neither work, getting the same error message.
Mick
PS Even tried having my rift on with Oculus software running and it's no different.

**Comment by Hotrian** [comment]
This does work on Rift, but only through SteamVR - without SteamVR nothing will happen. I'm using SteamVR API calls to make the magic happen, and I don't believe the Oculus SDK has support for Overlays, so I don't have any plans to make an Oculus SDK version.

It sounds like you are getting the archive preview - where Windows opens the archive as a folder, and allows you to see the contents. Can you try dragging the files out to your Desktop, then running the exe from there? That should get rid of the Data folder issue, though you'll still be unable to use it without SteamVR, or some other OpenVR implementation (though I'm unaware of any).

As for the differences between my link and Bumble's, I linked the 1.0.6 release directly, where as Bumble probably linked the main release page which shows all of the releases, but either page should work fine, as they are the same version of 1.0.6.

**Comment by Hotrian** [comment]
Also to be specific, this should work on Rift on any game that you run through SteamVR. Certain games however, like Elite Dangerous, will insist on using the Oculus SDK even when you tell them to run through SteamVR. [Here is a guide to getting ED to run on Rift with the SteamVR SDK](https://www.reddit.com/r/EliteDangerous/comments/53j9ka/openvrdesktopdisplayportal_overlay_for_oculus/), this will allow you to use ED with OVRDDP, though you'll trade ATW/ASW for Reprojection.

It might be possible to run your Oculus Home games using [Revive](https://github.com/LibreVR/Revive) to get them running through SteamVR, but I haven't tested this with a Rift so I have no idea if this will work - it was reported not to work with ED because ED does a Headset Check and forces Oculus SDK if you are using a Rift.

Without Revive, I assume Oculus Home games are incompatible because they use the Oculus SDK and not SteamVR.

Any SteamVR games should be 100% compatible however, as long as they aren't forcing the Oculus SDK like ED does. I believe ED and Subnautica are the only two games that do this, but I can't say for sure.

**Comment by mwal0120** [comment]
Thanks for all this. I think I'll leave things as they are here, if it isn't broke don't fix it. It's mainly ED that I play using my DK2 Rift and as you correctly say it uses SDK. However, it is worth mentioning that dragging the .exe file and the folder to my desktop WORKED. I have in the past used SteamVR to power ED and my rift when Oculus but I can't remember how I did it, in the future, when my DK2 ceases to work properly I'll perhaps go for a CV1.
Many thanks for your prompt replies and your help.
